config/routes.rb
Rails.application.routes.draw do
  get "homes/index"
  root "homes#index"
  resources :teacher_cohorts
  resources :student_cohorts
  resources :students
  resources :teachers
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course
  has_many :student_cohorts
  has_many :teacher_cohorts
  has_many :students, through: :student_cohorts
  has_many :teachers, through: :teacher_cohorts
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  has_many :students, through: :cohorts
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_cohorts
  has_many :cohorts, through: :student_cohorts

  def student_full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/student_cohort.rb
class StudentCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_cohorts
  has_many :cohorts, through: :teacher_cohorts

  def teacher_full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/teacher_cohort.rb
class TeacherCohort < ApplicationRecord
  belongs_to :teacher
  belongs_to :cohort
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new
  end

  def edit
    @cohort = Cohort.find(params[:id])

    @student_cohort_remove = StudentCohort.find_by(cohort_id: params[:id])
    @teacher_cohort_remove = StudentCohort.find_by(cohort_id: params[:id])
    
    if TeacherCohort.find_by(cohort_id: params[:id])
      @teacher_cohort = TeacherCohort.find_by(cohort_id: params[:id])
    else 
      @teacher_cohort = TeacherCohort.new
    end

    if StudentCohort.find_by(cohort_id: params[:id])
      @student_cohort = StudentCohort.find_by(cohort_id: params[:id])
    else 
      @student_cohort = StudentCohort.new
    end

    
  end

  def create


    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @cohort = Cohort.find(params[:id])
	
   if @cohort.update_attributes(cohort_params)
      redirect_to :action => 'show', :id => @cohort
   else
      render :action => 'edit'
   end

  end

  def destroy
    Cohort.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :course_id)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
    @cohorts = Cohort.all
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @course = Course.find(params[:id])
	
   if @course.update_attributes(course_params)
      redirect_to :action => 'show', :id => @course
   else
      render :action => 'edit'
   end
  end

  def destroy
    Course.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def course_params
    params.require(:course).permit(:name, :total_in_class_hours)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/student_cohorts_controller.rb
class StudentCohortsController < ApplicationController
  def edit
    @student_cohort = StudentCohort.find(params[:id])  
  end

  def update
    @student_cohort = StudentCohort.find(params[:id])
	
   if @student_cohort.update_attributes(student_cohort_params)
      redirect_to cohorts_url
   else
      render :action => 'edit'
   end
  end

  def create
    @student_cohort = StudentCohort.new(student_cohort_params)

    if @student_cohort.save
      redirect_to cohorts_url 
    else
      render :action => 'new'
    end
  end

  def destroy
    studentCohort.find(params[:id]).destroy
    redirect_to cohorts_url 
  end

private

  def student_cohort_params
    params.require(:student_cohort).permit(:student_id, :cohort_id)
  end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @cohorts = Cohort.all
    
  end

  def edit
    @student = Student.find(params[:id])
    @cohorts = Cohort.all
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @student = Student.find(params[:id])
	
   if @student.update_attributes(student_params)
      redirect_to :action => 'show', :id => @student
   else
      render :action => 'edit'
   end

  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to :action => 'index'
  end



  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :highest_completed_education)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def edit
    @teacher = Teacher.find(params[:id])  
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @teacher = Teacher.find(params[:id])
	
   if @teacher.update_attributes(teacher_params)
      redirect_to :action => 'show', :id => @teacher
   else
      render :action => 'edit'
   end
  end

  def destroy
    Teacher.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :age, :salary, :highest_completed_education)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_cohorts_helper.rb
module StudentCohortsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_cohorts_helper.rb
module TeacherCohortsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/cohorts/edit.html.erb
<%= bootstrap_form_with(model: @cohort, local: true) do |f| %>
<%= f.text_field :name, label: "Name:" %>
<%= f.date_field :start_date %>
<%= f.date_field :end_date %>
<%= f.collection_select(:course_id, Course.all, :id, :name) %>
<%= f.submit "Update Cohort" %>
<% end %>

<%= bootstrap_form_for(@teacher_cohort) do |f| %>
  <%= f.collection_select(:teacher_id, Teacher.all, :id, :teacher_full_name) %>
  <%= f.hidden_field(:cohort_id, value: "#{@cohort.id}") %>
  <%= f.submit "Add Teacher to Cohort" %>
<% end %>

<%= bootstrap_form_for(@student_cohort) do |f| %>
  <%= f.collection_select(:student_id, Student.all, :id, :student_full_name) %>
  <%= f.hidden_field(:cohort_id, value: "#{@cohort.id}") %>
  <%= f.submit "Add Student to Cohort" %>
<% end %>

app/views/cohorts/index.html.erb
<h1>All Cohorts</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    <% @cohorts.each do |cohort| %>
      <tr>
        <th scope="row"><%= cohort.id %></th>
        <td><%= cohort.name %></d>
        <td><%= cohort.start_date %></td>
        <td><%= cohort.end_date %></td>
        <td><%= link_to "Show Cohort", cohort %></td>
        <td><%= link_to "Edit Cohort", edit_cohort_path(cohort) %></td>
        <td><%= link_to "Delete Cohort", cohort, method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/cohorts/new.html.erb
<%= bootstrap_form_with(model: @cohort, local: true) do |f| %>
<%= f.text_field :name, label: "Name:" %>
<%= f.date_field :start_date %>
<%= f.date_field :end_date %>
<%= f.collection_select(:course_id, Course.all, :id, :name) %>
<%= f.submit "Create Cohort" %>
<% end %>

app/views/cohorts/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @cohort.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Start Date: <%= @cohort.start_date %></h6>
    <h6 class="card-subtitle mb-2 text-muted">End Date: <%= @cohort.end_date %></h6>
    <h5 class="card-title">Teachers</h5>
    <% @cohort.teachers.each do |teacher| %>
    <p class="card-text"><%= teacher.id %>. <%= teacher.first_name %> <%= teacher.last_name %></p>
    <% end %>
    <h5 class="card-title">Students</h5>
    <% @cohort.students.each do |student| %>
    <p class="card-text"><%= student.id %>. <%= student.first_name %> <%= student.last_name %></p>
    <% end %>
    <%= link_to "Edit Cohort", edit_cohort_path(@cohort), class: "card-link" %>
  </div>
</div>

app/views/homes/index.html.erb
<h1>Welcome to</h1>
<h1>School Tools!</h1>

app/views/students/edit.html.erb
<%= bootstrap_form_with(model: @student, local: true) do |f| %>
<%= f.text_field :first_name, label: "First Name:" %>
<%= f.text_field :last_name, label: "Last Name:" %>
<%= f.number_field :age, label: "Age:" %>
<%= f.text_field :highest_completed_education, label: "Highest Completed Education:" %>
<%= f.submit "Update Student" %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Age</th>
        <th scope="col">Highest Completed Education</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    <% @students.each do |student| %>
      <tr>
        <th scope="row"><%= student.id %></th>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.age %></td>
        <td><%= student.highest_completed_education %></td>
        <td><%= link_to "Show Student", student %></td>
        <td><%= link_to "Edit Student", edit_student_path(student) %></td>
        <td><%= link_to "Delete Student", student, method: :delete %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

app/views/students/new.html.erb
<%= bootstrap_form_with(model: @student, local: true) do |f| %>
<%= f.text_field :first_name, label: "First Name:" %>
<%= f.text_field :last_name, label: "Last Name:" %>
<%= f.select :age, (12..60), label: "Age:" %>
<%= f.select :highest_completed_education, ["high-school", "college", "masters", "PhD"], label: "Highest Completed Education:" %>
<%= f.submit "Create Student" %>
<% end %>

app/views/students/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @student.first_name %> <%= @student.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Age: <%= @student.age %></h6>
    <h6 class="card-subtitle mb-2 text-muted">Highest Completed Education: <%= @student.highest_completed_education %></h6>
    <h5 class="card-title">Cohorts</h5>
    <% @student.cohorts.each do |cohort| %>
    <p class="card-text"><%= cohort.id %>. <%= cohort.name %></p>
    <% end %>
    <%= link_to "Edit Student", edit_student_path(@student), class: "card-link" %>
  </div>
</div>

app/views/teachers/edit.html.erb
<%= bootstrap_form_with(model: @teacher, local: true) do |f| %>
<%= f.text_field :first_name, label: "First Name:" %>
<%= f.text_field :first_name, label: "First Name:" %>
<%= f.number_field :age, label: "Age:" %>
<%= f.number_field :salary, label: "Salary:" %>
<%= f.text_field :highest_completed_education, label: "Highest Completed Education:" %>
<%= f.submit "Update Teacher" %>
<% end %>

app/views/teachers/index.html.erb
<h1>All Teachers</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Age</th>
        <th scope="col">Salary</th>
        <th scope="col">Highest Completed Education</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <th scope="row"><%= teacher.id %></th>
        <td><%= teacher.first_name %></d>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.age %></td>
        <td><%= teacher.salary %></td>
        <td><%= teacher.highest_completed_education %></td>
        <td><%= link_to "Show Teacher", teacher %></td>
        <td><%= link_to "Edit Teacher", edit_teacher_path(teacher) %></td>
        <td><%= link_to "Delete Teacher", teacher, method: :delete %></td>
      <% end %>
      </tr>
    </tbody>
  </table>

app/views/teachers/new.html.erb
<%= bootstrap_form_with(model: @teacher, local: true) do |f| %>
<%= f.text_field :first_name, label: "First Name:" %>
<%= f.text_field :last_name, label: "Last Name:" %>
<%= f.select :age, (20..80), label: "Age:" %>
<%= f.select :salary, [50000, 55000, 60000, 65000, 75000], label: "Salary:" %>
<%= f.select :highest_completed_education, ["high-school", "college", "masters", "PhD"], label: "Highest Completed Education:" %>
<%= f.submit "Create Teacher" %>
<% end %>

app/views/teachers/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @teacher.first_name %> <%= @teacher.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Age: <%= @teacher.age %></h6>
    <h6 class="card-subtitle mb-2 text-muted">Salary: <%= @teacher.salary %></h6>
    <h6 class="card-subtitle mb-2 text-muted">Highest Completed Education: <%= @teacher.highest_completed_education %></h6>
    <% @teacher.cohorts.each do |cohort| %>
    <p class="card-text"><%= cohort.id %>. <%= cohort.name %></p>
    <% end %>
    <%= link_to "Edit Teacher", edit_student_path(@teacher), class: "card-link" %>
  </div>
</div>