config/routes.rb
Rails.application.routes.draw do
  get "homes/index"
  root "homes#index"
  resources :teacher_cohorts
  resources :student_cohorts
  resources :students
  resources :teachers
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course
  has_many :student_cohorts
  has_many :teacher_cohorts
  has_many :students, through: :student_cohorts
  has_many :teachers, through: :teacher_cohorts
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  has_many :students, through: :cohorts
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_cohorts
  has_many :cohorts, through: :student_cohorts

  def student_full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/student_cohort.rb
class StudentCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_cohorts
  has_many :cohorts, through: :teacher_cohorts

  def teacher_full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/teacher_cohort.rb
class TeacherCohort < ApplicationRecord
  belongs_to :teacher
  belongs_to :cohort
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new
  end

  def edit
    @cohort = Cohort.find(params[:id])

    @student_cohort_remove = StudentCohort.find_by(cohort_id: params[:id])
    @teacher_cohort_remove = StudentCohort.find_by(cohort_id: params[:id])
    
    if TeacherCohort.find_by(cohort_id: params[:id])
      @teacher_cohort = TeacherCohort.find_by(cohort_id: params[:id])
    else 
      @teacher_cohort = TeacherCohort.new
    end

    if StudentCohort.find_by(cohort_id: params[:id])
      @student_cohort = StudentCohort.find_by(cohort_id: params[:id])
    else 
      @student_cohort = StudentCohort.new
    end

    
  end

  def create


    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @cohort = Cohort.find(params[:id])
	
   if @cohort.update_attributes(cohort_params)
      redirect_to :action => 'show', :id => @cohort
   else
      render :action => 'edit'
   end

  end

  def destroy
    Cohort.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :course_id)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
    @cohorts = Cohort.all
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @course = Course.find(params[:id])
	
   if @course.update_attributes(course_params)
      redirect_to :action => 'show', :id => @course
   else
      render :action => 'edit'
   end
  end

  def destroy
    Course.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def course_params
    params.require(:course).permit(:name, :total_in_class_hours)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @cohorts = Cohort.all
    
  end

  def edit
    @student = Student.find(params[:id])
    @cohorts = Cohort.all
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @student = Student.find(params[:id])
	
   if @student.update_attributes(student_params)
      redirect_to :action => 'show', :id => @student
   else
      render :action => 'edit'
   end

  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to :action => 'index'
  end



  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :highest_completed_education)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def edit
    @teacher = Teacher.find(params[:id])  
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @teacher = Teacher.find(params[:id])
	
   if @teacher.update_attributes(teacher_params)
      redirect_to :action => 'show', :id => @teacher
   else
      render :action => 'edit'
   end
  end

  def destroy
    Teacher.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :age, :salary, :highest_completed_education)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_cohorts_helper.rb
module StudentCohortsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_cohorts_helper.rb
module TeacherCohortsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/courses/edit.html.erb
<%= bootstrap_form_with(model: @course, local: true) do |f| %>
  <%= f.text_field :name, label: "Name:" %>
  <%= f.text_field :total_in_class_hours, label: "Total hours in class:"  %>
  <%= f.submit "Update Course" %>
<% end %>

app/views/courses/index.html.erb
<h1>All Courses</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Total Hours in Class</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <th scope="row"><%= course.id %></th>
        <td><%= course.name %></d>
        <td><%= course.total_in_class_hours %></td>
        <td><%= link_to "Show Course", course %></td>
        <td><%= link_to "Edit Course", edit_course_path(course) %></td>
        <td><%= link_to "Delete Course", course, method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/courses/new.html.erb
<%= bootstrap_form_with(model: @course, local: true) do |f| %>
  <%= f.text_field :name, label: "Name:" %>
  <%= f.number_field :total_in_class_hours, label: "Total hours in class:"  %>
  <%= f.submit "Create Course" %>
<% end %>

app/views/courses/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @course.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Hours In Class: <%= @course.total_in_class_hours %></h6>
    <h5 class="card-title">Cohorts</h5>
    <% @course.cohorts.each do |cohort| %>
    <p class="card-text"><%= cohort.id %>. <%= link_to "#{cohort.name}", cohort_path(cohort.id) %> </p>
    <% end %> 
    <%= link_to "Edit course", edit_course_path(@course), class: "card-link" %>
  </div>
</div>