config/routes.rb
Rails.application.routes.draw do
  get "homes/index"
  root "homes#index"
  resources :teacher_cohorts
  resources :student_cohorts
  resources :students
  resources :teachers
  resources :courses
  resources :cohorts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course
  has_many :student_cohorts
  has_many :teacher_cohorts
  has_many :students, through: :student_cohorts
  has_many :teachers, through: :teacher_cohorts
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
  has_many :students, through: :cohorts
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_cohorts
  has_many :cohorts, through: :student_cohorts

  def student_full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/student_cohort.rb
class StudentCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_cohorts
  has_many :cohorts, through: :teacher_cohorts

  def teacher_full_name
    "#{first_name} #{last_name}"
  end
  
end

app/models/teacher_cohort.rb
class TeacherCohort < ApplicationRecord
  belongs_to :teacher
  belongs_to :cohort
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
    @cohorts = Cohort.all
  end

  def show
    @cohort = Cohort.find(params[:id])
  end

  def new
    @cohort = Cohort.new
  end

  def edit
    @cohort = Cohort.find(params[:id])

    @student_cohort_remove = StudentCohort.find_by(cohort_id: params[:id])
    @teacher_cohort_remove = StudentCohort.find_by(cohort_id: params[:id])
    
    if TeacherCohort.find_by(cohort_id: params[:id])
      @teacher_cohort = TeacherCohort.find_by(cohort_id: params[:id])
    else 
      @teacher_cohort = TeacherCohort.new
    end

    if StudentCohort.find_by(cohort_id: params[:id])
      @student_cohort = StudentCohort.find_by(cohort_id: params[:id])
    else 
      @student_cohort = StudentCohort.new
    end

    
  end

  def create


    @cohort = Cohort.new(cohort_params)

    if @cohort.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @cohort = Cohort.find(params[:id])
	
   if @cohort.update_attributes(cohort_params)
      redirect_to :action => 'show', :id => @cohort
   else
      render :action => 'edit'
   end

  end

  def destroy
    Cohort.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :course_id)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
    @cohorts = Cohort.all
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @course = Course.find(params[:id])
	
   if @course.update_attributes(course_params)
      redirect_to :action => 'show', :id => @course
   else
      render :action => 'edit'
   end
  end

  def destroy
    Course.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def course_params
    params.require(:course).permit(:name, :total_in_class_hours)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @cohorts = Cohort.all
    
  end

  def edit
    @student = Student.find(params[:id])
    @cohorts = Cohort.all
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end

  end

  def update
    @student = Student.find(params[:id])
	
   if @student.update_attributes(student_params)
      redirect_to :action => 'show', :id => @student
   else
      render :action => 'edit'
   end

  end

  def destroy
    Student.find(params[:id]).destroy
    redirect_to :action => 'index'
  end



  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :highest_completed_education)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_cohorts_helper.rb
module StudentCohortsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_cohorts_helper.rb
module TeacherCohortsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolPanel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-light nav-fill border-bottom">
      <%= link_to image_tag("toolkit.png"), root_path %> <h1> School Tools </h1>
        <ul class="nav nav-tabs">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Courses</a>
          <div class="dropdown-menu">
              <%= link_to "All Courses", courses_path, class: "dropdown_item" %>
          <div class="dropdown-divider"></div>
              <%= link_to "Create Course", new_course_path, class: "dropdown_item" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cohorts</a>
          <div class="dropdown-menu">
            <%= link_to "All Cohorts", cohorts_path, class: "dropdown_item" %>
          <div class="dropdown-divider"></div>
              <%= link_to "Create Cohort", new_cohort_path, class: "dropdown_item" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Teachers</a>
          <div class="dropdown-menu">
              <%= link_to "All Teachers", teachers_path, class: "dropdown_item" %>
          <div class="dropdown-divider"></div>
              <%= link_to "Create Teacher", new_teacher_path, class: "dropdown_item" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Students</a>
            <div class="dropdown-menu">
              <%= link_to "All Students", students_path, class: "dropdown_item" %>
          <div class="dropdown-divider"></div>
              <%= link_to "Create Student", new_student_path, class: "dropdown_item" %>
          </li>
        </ul>
    </nav>

<%= yield %>


  </body>
</html>